function g = g_fun_solution(in1)
%G_FUN_SOLUTION
%    G = G_FUN_SOLUTION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    17-Oct-2017 14:53:29

phi2 = in1(2,:);
phi3 = in1(3,:);
phi4 = in1(4,:);
phi5 = in1(5,:);
t2 = phi2+phi3;
t3 = cos(t2);
t4 = sin(t2);
t5 = cos(phi4);
t6 = cos(phi5);
t7 = sin(phi5);
t8 = t4.*t5.*t7.*9.88848e-3;
g = [0.0;t3.*(-1.760431968e1)-t4.*2.1334788+t8-sin(phi2).*1.72094868e1-t3.*t6.*9.88848e-3-t4.*t5.*8.9271e-1-t3.*t7.*1.61865e-1-t4.*t5.*t6.*1.61865e-1;t3.*(-1.760431968e1)-t4.*2.1334788+t8-t3.*t6.*9.88848e-3-t4.*t5.*8.9271e-1-t3.*t7.*1.61865e-1-t4.*t5.*t6.*1.61865e-1;t3.*sin(phi4).*(t6.*4.125e3-t7.*2.52e2+2.275e4).*(-3.924e-5);t4.*t6.*(-1.61865e-1)+t4.*t7.*9.88848e-3-t3.*t5.*t6.*9.88848e-3-t3.*t5.*t7.*1.61865e-1;0.0];
