function out1 = I_r_IE_fun_solution(in1)
%I_R_IE_FUN
%    OUT1 = I_R_IE_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    19-Oct-2016 00:58:54

phi1 = in1(1,:);
phi2 = in1(2,:);
phi3 = in1(3,:);
phi4 = in1(4,:);
phi5 = in1(5,:);
t2 = cos(phi1);
t3 = phi2+phi3;
t4 = sin(t3);
t5 = cos(t3);
t6 = sin(phi5);
t7 = sin(phi4);
t8 = cos(phi4);
t9 = sin(phi1);
t10 = t5.*1.51e2;
t11 = t4.*3.5e1;
t12 = sin(phi2);
t13 = t12.*1.35e2;
t14 = t10+t11+t13;
t15 = cos(phi5);
out1 = [t6.*(t7.*t9+t2.*t4.*t8).*(-9.0./1.25e2)+t2.*t14.*(1.0./5.0e2)+t2.*t5.*t15.*(9.0./1.25e2);t6.*(t2.*t7-t4.*t8.*t9).*(9.0./1.25e2)+t9.*t14.*(1.0./5.0e2)+t5.*t9.*t15.*(9.0./1.25e2);t4.*(-1.51e2./5.0e2)+t5.*(7.0./1.0e2)+cos(phi2).*(2.7e1./1.0e2)-t4.*t15.*(9.0./1.25e2)-t5.*t6.*t8.*(9.0./1.25e2)+2.9e1./1.0e2];
