function out1 = I_r_IE_fun(in1)
%I_R_IE_FUN
%    OUT1 = I_R_IE_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-Nov-2020 21:46:42

phi1 = in1(1,:);
phi2 = in1(2,:);
phi3 = in1(3,:);
phi4 = in1(4,:);
phi5 = in1(5,:);
t2 = cos(phi1);
t3 = cos(phi4);
t4 = cos(phi5);
t5 = sin(phi1);
t6 = sin(phi2);
t7 = sin(phi4);
t8 = sin(phi5);
t9 = phi2+phi3;
t10 = cos(t9);
t11 = sin(t9);
t12 = t6.*1.35e+2;
t13 = t11.*3.5e+1;
t14 = t10.*1.51e+2;
t15 = t12+t13+t14;
out1 = [t8.*(t5.*t7+t2.*t3.*t11).*(-9.0./1.25e+2)+(t2.*t15)./5.0e+2+t2.*t4.*t10.*(9.0./1.25e+2);t8.*(t2.*t7-t3.*t5.*t11).*(9.0./1.25e+2)+(t5.*t15)./5.0e+2+t4.*t5.*t10.*(9.0./1.25e+2);t10.*(7.0./1.0e+2)-t11.*(1.51e+2./5.0e+2)+cos(phi2).*(2.7e+1./1.0e+2)-t4.*t11.*(9.0./1.25e+2)-t3.*t8.*t10.*(9.0./1.25e+2)+2.9e+1./1.0e+2];
