function out1 = T_IE_fun(in1)
%T_IE_FUN
%    OUT1 = T_IE_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-Nov-2020 21:46:43

phi1 = in1(1,:);
phi2 = in1(2,:);
phi3 = in1(3,:);
phi4 = in1(4,:);
phi5 = in1(5,:);
phi6 = in1(6,:);
t2 = cos(phi1);
t3 = cos(phi4);
t4 = cos(phi5);
t5 = cos(phi6);
t6 = sin(phi1);
t7 = sin(phi2);
t8 = sin(phi4);
t9 = sin(phi5);
t10 = sin(phi6);
t11 = phi2+phi3;
t12 = cos(t11);
t13 = sin(t11);
t14 = t2.*t3;
t15 = t2.*t8;
t16 = t3.*t6;
t17 = t6.*t8;
t18 = t7.*1.35e+2;
t19 = t13.*3.5e+1;
t20 = t9.*t13;
t21 = t12.*1.51e+2;
t22 = t3.*t4.*t12;
t23 = t13.*t14;
t24 = t2.*t9.*t12;
t25 = t13.*t15;
t26 = t13.*t16;
t27 = t6.*t9.*t12;
t28 = t13.*t17;
t29 = -t22;
t30 = -t25;
t31 = -t26;
t32 = -t27;
t33 = t14+t28;
t34 = t17+t23;
t40 = t18+t19+t21;
t35 = t15+t31;
t36 = t16+t30;
t37 = t4.*t34;
t38 = t20+t29;
t39 = t4.*t35;
t41 = t24+t37;
t42 = t32+t39;
out1 = reshape([-t9.*t34+t2.*t4.*t12,t9.*t35+t4.*t6.*t12,-t4.*t13-t3.*t9.*t12,0.0,-t5.*t36+t10.*t41,t5.*t33+t10.*(t27-t39),-t10.*t38+t5.*t8.*t12,0.0,t5.*t41+t10.*t36,-t10.*t33+t5.*(t27-t39),-t5.*t38-t8.*t10.*t12,0.0,(t2.*t40)./5.0e+2-t9.*t34.*(9.0./1.25e+2)+t2.*t4.*t12.*(9.0./1.25e+2),t9.*t35.*(9.0./1.25e+2)+(t6.*t40)./5.0e+2+t4.*t6.*t12.*(9.0./1.25e+2),t12.*(7.0./1.0e+2)-t13.*(1.51e+2./5.0e+2)+cos(phi2).*(2.7e+1./1.0e+2)-t4.*t13.*(9.0./1.25e+2)-t3.*t9.*t12.*(9.0./1.25e+2)+2.9e+1./1.0e+2,1.0],[4,4]);
