function I_r_IE = jointToPosition_solution(q)
  % Input: joint angles
  % Output: position of end-effector w.r.t. inertial frame. I_r_IE
	T_IE = getTransformI0_solution()*...
           jointToTransform01_solution(q)*...
           jointToTransform12_solution(q)*...
           jointToTransform23_solution(q)*...
           jointToTransform34_solution(q)*...
           jointToTransform45_solution(q)*...
           jointToTransform56_solution(q)*...
           getTransform6E_solution();
    I_r_IE = T_IE(1:3,4);
end